name: .NET Core

on:
  push:
    branches: [main, vnext]
  pull_request:
    branches: [main, vnext]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "10.0.x"
      - name: Restore
        run: dotnet restore
      - name: Build
        run: dotnet build Migrondi.slnx --configuration Release --no-restore
      - name: Test
        run: dotnet test Migrondi.slnx --no-build --configuration Release --verbosity normal
